language: cpp
os:
  - linux
  - osx
env:
  - BUILD_TYPE=Release GENERATOR=Ninja MAKER=ninja
  - BUILD_TYPE=Debug GENERATOR=Ninja MAKER=ninja
  - BUILD_TYPE=Release GENERATOR="Unix Makefiles" MAKER=make
  - BUILD_TYPE=Debug GENERATOR="Unix Makefiles" MAKER=make
compiler:
  - gcc
  - clang
before_install:
  - test "$TRAVIS_OS_NAME" = "linux" && sudo add-apt-repository --yes ppa:andykimpe/cmake || echo "NOT adding apt repo."
  - test "$TRAVIS_OS_NAME" = "linux" && sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots  || echo "NOT adding apt repo."
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get update -qq  || echo "NOT updating apt repo."
install:
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get install -y cmake ninja-build || echo "NOT installing from apt."
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get install -y libopenal-dev libogg-dev libvorbis-dev build-essential libsdl2-dev libtheora-dev libreadline6-dev libpng12-dev libjpeg62-dev liblua5.1-0-dev libjansson-dev libtool doxygen || echo "NOT installing from apt."
  - test "$TRAVIS_OS_NAME" = "osx" && brew install pkg-config ninja sdl2 theora libogg libvorbis openal-soft || echo "NOT osx."
before_script:
  - cmake --version
  - mkdir travis-build
script:
  - test "$TRAVIS_OS_NAME" = "osx" && export OPENALDIR=/usr/local/Cellar/openal-soft/1.16.0 || echo "NOT setting OPENALDIR."
  - cd travis-build
  - cmake -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - $MAKER
branches:
  only: cmake-travis
notifications:
  irc:
    channels: "irc.esper.net#Diaspora"
    on_success: change
    on_failure: change
