language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:andykimpe/cmake
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y cmake ninja-build
  - sudo apt-get install -y libopenal-dev libogg-dev libvorbis-dev build-essential libsdl2-dev libtheora-dev libreadline6-dev libpng12-dev libjpeg62-dev liblua5.1-0-dev libjansson-dev libtool doxygen
before_script:
  - cmake --version
  - mkdir travis-build
script: cd travis-build && cmake -G Ninja .. && ninja
branches:
  only: cmake-travis
notifications:
  irc:
    channels: "irc.esper.net#Diaspora"
    on_success: change
    on_failure: change
