version: 1.0.{build}
branches:
  only:
  - cmake-travis
configuration:
  - Debug
  - Release
environment:
  matrix:
  - VS_VERSION: 11
  - VS_VERSION: 12
install:
  - cinst wget
  - wget -nv -O wxWidgets_Headers.7z "http://sourceforge.net/projects/wxwindows/files/3.0.2/wxWidgets-3.0.2_headers.7z/download"
  - wget -nv -O wxMSW_DLL.7z "http://sourceforge.net/projects/wxwindows/files/3.0.2/binaries/wxMSW-3.0.2_vc%VS_VERSION%0_ReleaseDLL.7z/download"
  - wget -nv -O wxMSW_Dev.7z "http://sourceforge.net/projects/wxwindows/files/3.0.2/binaries/wxMSW-3.0.2_vc%VS_VERSION%0_Dev.7z/download"
  - dir
  - mkdir C:\wxWidgets
  - 7z x -oC:\wxWidgets -y wxWidgets_Headers.7z
  - 7z x -oC:\wxWidgets -y wxMSW_DLL.7z
  - 7z x -oC:\wxWidgets -y wxMSW_Dev.7z
  - dir C:\wxWidgets
  - dir C:\wxWidgets\lib
  - move C:\wxWidgets\lib\vc%VS_VERSION%0_dll C:\wxWidgets\lib\vc_dll
before_build:
  - cmake -G "Visual Studio %VS_VERSION%" -DFSO_BUILD_WXFRED2=ON
  - dir
build:
  project: FS2_Open.sln
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)
    name: fso-continuous-$(configuration)-vs$(VS_VERSION)
