version: 1.0.{build}
branches:
  only:
  - cmake-travis
configuration:
  - Debug
  - Release
environment:
  matrix:
  - VS_VERSION: Visual Studio 9 2008
  - VS_VERSION: Visual Studio 10
  - VS_VERSION: Visual Studio 11
  - VS_VERSION: Visual Studio 12

before_build:
  - cmake -G %VS_VERSION%
  - dir
build:
  project: FS2_Open.sln
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)
    name: fso-continuous-$(configuration)
