version: 1.0.{build}
branches:
  only:
  - cmake-travis
configuration:
  - Debug
  - Release
environment:
  matrix:
  - VS_VERSION: 11
  - VS_VERSION: 12
before_build:
  - cmake -G "Visual Studio %VS_VERSION%"
  - dir
build:
  project: FS2_Open.sln
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)
    name: fso-continuous-$(configuration)-vs$(VS_VERSION)
