version: 1.0.{build}
branches:
  only:
  - cmake-travis
configuration:
  - Debug
  - Release
environment:
  matrix:
  - VS_VERSION: 11
  - VS_VERSION: 12
install:
  - cinst wget
  - wget -nv -O wxMSW_DLL.7z "http://sourceforge.net/projects/wxwindows/files/3.0.2/binaries/wxMSW-3.0.2_vc%VS_VERSION%0_ReleaseDLL.7z/download"
  - wget -nv -O wxMSW_Dev.7z "http://sourceforge.net/projects/wxwindows/files/3.0.2/binaries/wxMSW-3.0.2_vc%VS_VERSION%0_Dev.7z/download"
  - dir
  - mkdir wxWidgets-3.0.2
  - 7z e -owxWidgets-3.0.2 -y wxMSW_DLL.7z
  - 7z e -owxWidgets-3.0.2 -y wxMSW_Dev.7z
  - dir wxWidgets-3.0.2
before_build:
  - cmake -G "Visual Studio %VS_VERSION%" -DFSO_BUILD_WXFRED2=ON -DwxWidgets_ROOT_DIR=%APPVEYOR_BUILD_FOLDER%/wxWidgets-3.0.2
  - dir
build:
  project: FS2_Open.sln
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)
    name: fso-continuous-$(configuration)-vs$(VS_VERSION)
