version: 1.0.{build}
branches:
  only:
  - cmake-travis
configuration:
  - Debug
  - Release
environment:
  matrix:
  - VS_VERSION: 11
  - VS_VERSION: 12
install:
  - choco install wxwidgets
before_build:
  - cmake -G "Visual Studio %VS_VERSION%" -DFSO_BUILD_WXFRED2=ON -DwxWidgets_ROOT_DIR=C:/wxWidgets-3.0.2
  - dir
build:
  project: FS2_Open.sln
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)
    name: fso-continuous-$(configuration)-vs$(VS_VERSION)
