
IF(MSVC)
	IF(MSVC_USE_RUNTIME_DLL)
		SET(Boost_USE_STATIC_RUNTIME FALSE)
	ELSE(MSVC_USE_RUNTIME_DLL)
		SET(Boost_USE_STATIC_RUNTIME TRUE)
	ENDIF(MSVC_USE_RUNTIME_DLL)
ENDIF(MSVC)

SET(Boost_USE_STATIC_LIBS ON)

SET(VFSPP_NO_INSTALL TRUE)
ADD_SUBDIRECTORY(vfspp)

SET(VFSPP_LIBRARIES VFSPP CACHE INTERNAL "" FORCE)

set_target_properties(VFSPP
	PROPERTIES
		FOLDER "3rdparty"
)
