name: Publish Standalone docker image

on:
  push:
    branches:
      - '*'
    tags:
    - 'nightly_*'
    - 'release_*'

jobs:
  build_images:
    strategy:
      matrix:
        configuration: [FastDebug, Release]
        include:
        - configuration: FastDebug
          latest_tag: latest_debug
          nightly_tag: nightly_debug
          release_tag: release_debug
        - configuration: Release
          latest_tag: latest
          nightly_tag: nightly
          release_tag: release
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout
      with:
        submodules: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/scp-fs2open/standalone_server
        tag-sha: true
        tag-latest: false

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/standalone/Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          build_type=${{ matrix.configuration }}
